# Generated by Django 5.1.5 on 2025-02-01 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField()),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='BELUM', max_length=10)),
                ('jatuh_tempo_berikutnya', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
