# Generated by Django 5.1.5 on 2025-02-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KritikSaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('tanggal_dikirim', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kritik_saran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo Berikutnya')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(verbose_name='Tanggal Pembayaran')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Pembayaran')),
                ('metode_pembayaran', models.CharField(choices=[('bank_transfer', 'Transfer Bank'), ('e_wallet', 'E-Wallet')], max_length=20, verbose_name='Metode Pembayaran')),
                ('status', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='BELUM', max_length=20, verbose_name='Status Pembayaran')),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/', verbose_name='Bukti Transfer')),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Transaksi')),
                ('durasi_bayar', models.PositiveIntegerField(default=1, verbose_name='Durasi Bayar (Bulan)')),
                ('jenis_durasi', models.CharField(choices=[('per_bulan', 'Per Bulan'), ('per_tahun', 'Per Tahun')], max_length=10, verbose_name='Jenis Durasi Pembayaran')),
                ('status_validasi', models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10, verbose_name='Status Validasi Pembayaran')),
                ('tipe_kamar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to='main.tipekamar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
