# Generated by Django 5.1.5 on 2025-02-03 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='jatuh_tempo_berikutnya',
            field=models.DateField(verbose_name='Jatuh Tempo Berikutnya'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='jumlah_pembayaran',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='status',
            field=models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='BELUM', max_length=10, verbose_name='Status Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='tanggal_pembayaran',
            field=models.DateField(verbose_name='Tanggal Pembayaran'),
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(max_length=10, verbose_name='Bulan')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nominal Pembayaran')),
                ('metode_pembayaran', models.CharField(choices=[('bank_transfer', 'Transfer Bank'), ('e_wallet', 'E-Wallet')], max_length=20, verbose_name='Metode Pembayaran')),
                ('status', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='BELUM', max_length=20, verbose_name='Status Pembayaran')),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/', verbose_name='Bukti Transfer')),
                ('tanggal_transaksi', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Transaksi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Riwayat Transaksi',
                'verbose_name_plural': 'Riwayat Transaksi',
            },
        ),
    ]
