# Generated by Django 5.1.5 on 2025-03-05 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kritiksaran',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kritik_saran', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='tipe_kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to='main.tipekamar'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL),
        ),
    ]
