# Generated by Django 5.1.5 on 2025-02-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_pembayaran_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='bulan',
            field=models.CharField(max_length=13, verbose_name='Bulan'),
        ),
    ]
