# Generated by Django 5.1.5 on 2025-02-04 12:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_kritiksaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='jatuh_tempo_berikutnya',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='jumlah_pembayaran',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pembayaran',
            name='tanggal_pembayaran',
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='jatuh_tempo',
            field=models.DateField(default=datetime.date.today, verbose_name='Jatuh Tempo Berikutnya'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='durasi_bayar',
            field=models.PositiveIntegerField(default=1, verbose_name='Durasi Bayar (Bulan)'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='bulan',
            field=models.CharField(max_length=13, verbose_name='Bulan Pembayaran'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='LUNAS', max_length=20, verbose_name='Status Pembayaran'),
        ),
    ]
