# Generated by Django 5.1.5 on 2025-02-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_pembayaran_options_remove_transaksi_bulan'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='jenis_durasi',
            field=models.CharField(choices=[('per_bulan', 'Per Bulan'), ('per_tahun', 'Per Tahun')], default='per_bulan', max_length=10, verbose_name='Jenis Durasi Pembayaran'),
            preserve_default=False,
        ),
    ]
