# Generated by Django 5.1.5 on 2025-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_transaksi_jenis_durasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksi',
            options={},
        ),
        migrations.AddField(
            model_name='transaksi',
            name='status_validasi',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10, verbose_name='Status Validasi Pembayaran'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM', 'Belum Lunas')], default='BELUM', max_length=20, verbose_name='Status Pembayaran'),
        ),
    ]
