# Generated by Django 5.1.5 on 2025-02-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_transaksi_options_transaksi_status_validasi_and_more'),
        ('main', '0013_pemesanan_status_pemesanan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='pemesanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to='main.pemesanan'),
        ),
    ]
