# Generated by Django 5.1.5 on 2025-02-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_transaksi_pemesanan'),
        ('main', '0013_pemesanan_status_pemesanan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='pemesanan',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='tipe_kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to='main.tipekamar'),
        ),
    ]
