# Generated by Django 5.1.5 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipeKamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('fasilitas', models.TextField()),
                ('harga_per_bulan_1_orang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_per_bulan_2_orang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kamar/')),
            ],
        ),
    ]
