# Generated by Django 5.1.5 on 2025-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipekamar',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
