# Generated by Django 5.1.5 on 2025-03-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tipekamar_deskripsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipekamar',
            name='deskripsi',
        ),
    ]
