# Generated by Django 5.1.5 on 2025-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tipekamar_gambar_kamarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipekamar',
            name='harga_non_token',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tipekamar',
            name='harga_per_bulan_3_orang',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tipekamar',
            name='jumlah_kamar',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipekamar',
            name='max_penghuni',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipekamar',
            name='harga_per_bulan_2_orang',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
