# Generated by Django 5.1.5 on 2025-03-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_kamar_nomor_kamar_alter_kamar_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='kamar',
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='tipe_kamar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemesanan', to='main.tipekamar'),
        ),
    ]
