# Generated by Django 5.1.5 on 2025-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tipekamar_harga_non_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipekamar',
            old_name='harga_non_token',
            new_name='harga_non_token_1_orang',
        ),
        migrations.AddField(
            model_name='tipekamar',
            name='harga_non_token_2_orang',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tipekamar',
            name='harga_non_token_3_orang',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
