# Generated by Django 5.1.5 on 2025-03-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_pemesanan_kamar_pemesanan_tipe_kamar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penghuni', to='main.kamar'),
        ),
    ]
