# Generated by Django 5.1.5 on 2025-01-24 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_harga_non_token_tipekamar_harga_non_token_1_orang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kontak', models.CharField(max_length=255)),
                ('durasi', models.CharField(choices=[('bulanan', 'Bulanan'), ('tahunan', 'Tahunan')], max_length=50)),
                ('jumlah_penghuni', models.PositiveIntegerField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_pemesanan', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipe_kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemesanan', to='main.tipekamar')),
            ],
        ),
    ]
