# Generated by Django 5.1.5 on 2025-02-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_penghuni',
            field=models.BooleanField(default=False),
        ),
    ]
