# Generated by Django 5.1.5 on 2025-02-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_is_penghuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='tipe_sewa',
            field=models.CharField(choices=[('bulanan', 'Bulanan'), ('tahunan', 'Tahunan')], default='bulanan', max_length=10),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='durasi',
            field=models.PositiveIntegerField(help_text='Durasi dalam jumlah bulan atau tahun'),
        ),
    ]
