# Generated by Django 5.1.5 on 2025-02-13 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pemesanan_tipe_sewa_alter_pemesanan_durasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='menunggu', max_length=10),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pemesanan', to=settings.AUTH_USER_MODEL),
        ),
    ]
