# Generated by Django 5.1.5 on 2025-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pemesanan_status_pemesanan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tanggal_bergabung',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tanggal_keluar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
